feat: added --number, -n flags to list command
bakurits/fileshare pull request #7
Opened 2020-11-06 13:58 UTC by 3NFBAGDU

2020-11-06 14:02 UTC, bakurits requested changes

2020-11-06 14:02 UTC, bakurits commented on pkg/cmd/drivemanager/list.go
blank lines before error checks should be removed

2020-11-06 14:02 UTC, bakurits commented on pkg/cmd/drivemanager/list.go
> +
blank lines before error checks should be removed

2020-11-06 14:02 UTC, bakurits commented on pkg/drive/list.go
> +	return fileList[:ix.Min(fileNumber, len(fileList))], nil
The most used number of requested files will be 20. So maybe it would be better not to fetch all data from the drive and then remove extra ones.

2020-11-06 14:02 UTC, bakurits commented on pkg/drive/list.go
> +func (s *Service) List(fileNumber int) ([]*drive.File, error) {
`limit` would be a better name for `fileNumber`

2020-11-06 14:42 UTC, 3NFBAGDU commented on pkg/drive/list.go
> +	return fileList[:ix.Min(fileNumber, len(fileList))], nil
```
if nextPageToken == "" || len(fileList) >= limit {
	break
} 
this  piece of code will prevent this problem.

2020-11-08 06:57 UTC, bakurits reviewed
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bakurits/fileshare/7)* status: all files reviewed, 1 unresolved discussion (waiting on @3NFBAGDU)



<!-- Sent from Reviewable.io -->

2020-11-08 06:58 UTC, bakurits approved these changes
> *[Reviewable](https://reviewable.io/reviews/bakurits/fileshare/7)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-08 07:33 UTC, merged